- src/plotting_interactive.jl
- src/plotting_static.jl
- Plotting function now show plots and return dictionaries.
- Explicit markers keywords removed
- kwargs added consistently in all plotters
> plots return dictionaries

- Project.toml
- src/modules/LinearResponse/jacobian_spectrum.jl
Fixes #13 
Updated Symbolics to 3.4.1
> imshow -> pcolormesh in Jacobian plots

- Project.toml
- src/HarmonicBalance.jl
- src/hysteresis_sweep.jl
- src/plotting_static.jl
Tested. Renamed files a bit into a more "Julian" form
> functions to follow stable solutions (1D sweep)

- src/plotting_Plots.jl
> Add `branch` argument to the documentation

- src/modules/LinearResponse/plotting.jl
- src/solve_homotopy.jl
- src/sorting.jl
Resolves #68 
After looking at the code, I think it is maybe bad to implement a conditional allocation. I suspect this is, in general, discouraged. Review needed.
> Naive implementation of conditional allocation of ProgressBar

- src/HarmonicBalance.jl
- src/plotting_Plots.jl
resolves #61 
Now only ***one*** warning is presented if values with non-negligible complex parts have been projected on the real axis!
The function have become far more longer tho
> Realify warnings

- src/plotting_Plots.jl
- src/solve_homotopy.jl
- src/sorting.jl
> Plot documentation update

- src/HarmonicEquation.jl
- src/HarmonicVariable.jl
- src/modules/LinearResponse.jl
- src/modules/LinearResponse/Lorentzian_spectrum.jl
- src/modules/TimeEvolution/types.jl
- src/plotting_Plots.jl
- src/transform_solutions.jl
- src/types.jl
`plot` now has an optional kwarg `branches` for 1D plots  to specify which branches will be plotted. This prevents plots taking too long in problems with extremely high branch counts.
Closes #74
> Plots recipes

- .github/workflows/CI.yml
- Project.toml
> Fix symbolic version

- docs/make.jl
> Change mathengine to MathJax2

- .github/workflows/CI.yml
- Project.toml
- src/modules/LimitCycles/analysis.jl
- src/modules/LimitCycles/gauge_fixing.jl
- test/limit_cycle.jl
> Fix Limit cycle bug

- src/solve_homotopy.jl
- test/API.jl
> test: add some API tests

- src/plotting_Plots.jl
- test/plotting.jl
> test: 2d cuts ArgumentError

- src/ExprUtils/Symbolics_utils.jl
- src/HC_wrapper/homotopy_interface.jl
- src/HarmonicBalance.jl
- src/HarmonicEquation.jl
- src/transform_solutions.jl
- test/API.jl
- test/symbolics.jl
- test/transform_solutions.jl
> feat: `to_lab_frame` for multiple variables ansatz

- docs/src/manual/time_dependent.md
- docs/src/tutorials/limit_cycles.md
- docs/src/tutorials/time_dependent.md
- ext/TimeEvolution/ODEProblem.jl
- ext/TimeEvolution/TimeEvolution.jl
- ext/TimeEvolution/sweeps.jl
- src/HarmonicBalance.jl
- src/types.jl
- test/time_evolution.jl
> style: rename `ParameterSweep` to `AdiabaticSweep`

- docs/src/tutorials/time_dependent.md
- ext/TimeEvolution/ODEProblem.jl
- test/SteadyStateDiffEqExt.jl
- test/time_evolution.jl
> style: rename `x0` to be `u0` in line with `SciML`

- src/ExprUtils/Symbolics_utils.jl
- src/LinearResponse/response.jl
- test/linear_response.jl
> fix: make 2nd order response work and add some tests

- Project.toml
- test/Jacobian.jl
> test: add NaNMath tests

- .github/workflows/Documentation.yml
- docs/make.jl
- docs/src/examples/state_dependent_perturbation.md
- docs/src/manual/API.md
- docs/src/manual/entering_eom.md
- docs/src/manual/linear_response.md
- docs/src/manual/plotting.md
- ext/ModelingToolkitExt.jl
- ext/TimeEvolution/ODEProblem.jl
- ext/TimeEvolution/hysteresis_sweep.jl
- src/modules/LinearResponse/LinearResponse.jl
> docs: complete API list

- benchmark/3parametron.jl
- benchmark/JacobianFunction.jl
- benchmark/parametron.jl
- docs/src/examples/state_dependent_perturbation.md
- docs/src/manual/solving_harmonics.md
- examples/state_dependent_perturbation.jl
- src/HarmonicBalance.jl
- src/HarmonicEquation.jl
- src/Jacobian.jl
- src/Problem.jl
- src/Result.jl
- src/modules/ExprUtils/ExprUtils.jl
- src/modules/LimitCycles/LimitCycles.jl
- src/modules/LimitCycles/analysis.jl
- src/modules/LimitCycles/gauge_fixing.jl
- src/solve_homotopy.jl
- src/types.jl
- src/utils.jl
- test/API.jl
- test/Jacobian.jl
- test/Problem.jl
- test/code_quality.jl
- test/limit_cycle.jl
- test/runtests.jl
- test/steady_states/methods.jl
- test/steady_states/parametron.jl
> feat: add Jac to HarmonicEquation and compile Jac in Problem

- src/solve_homotopy.jl
- test/runtests.jl
- test/sorting.jl
resolves #329 and resolves #205
> feat: add verbose keyword the homotopy solver and test hilbert sorting

- src/DifferentialEquation.jl
- src/Problem.jl
> docs: small docs corrections

- src/Problem.jl
- src/modules/HC_wrapper.jl
- test/Problem.jl
> feat: new problem constructor

- examples/cumulants_KPO.jl
> fix: cumulant example

- Project.toml
> build: tag new breaking release

- Project.toml
> Tag patch release

- ext/QuantumCumulantsExt.jl
- test/extensions/QuantumCumulantsExt.jl
> fix: QC with rnumber

- Makefile
- README.md
- docs/make.jl
- docs/src/.vitepress/config.mts
- docs/src/examples/index.md
- docs/src/index.md
- docs/src/tutorials/index.md
- examples/README.md
- ext/SteadyStateDiffEqExt.jl
- test/Jacobian.jl
- test/extensions/SteadyStateDiffEqExt.jl
> chore: change organization name

- Project.toml
> chore: rm HSS [Sources] entry

- docs/src/tutorials/steady_states.md
> docs: fix typeo

- .github/workflows/Tests.yml
- README.md
> feat: add code coverage
